<-PYT:import urllib.request
<-PYT:urllib.request.__name__
->RET:'urllib.request'
<-PYT:urllib.request.__path__
->RET:raise AttributeError("module 'urllib.request' has no attribute '__path__'")
<-PYT:urllib.request.Request('https://dev.azure.com/fake/bogus/_apis/wit/workitems?ids=42&api-version=7.1-preview.3&fields=System.AssignedTo,System.AreaPath,System.CreatedDate,Microsoft.VSTS.Common.Severity,System.CreatedBy,System.State,System.ChangedDate,System.Title')
->RET:Instance('Request', 'request1')
<-PYT:request1.add_header('Authorization', 'Basic OmZha2VfcGF0')
<-PYT:urllib.request.urlopen(request1)
->RET:raise Instance('HTTPError(URLError, OSError)', 'httperror1')
<-PYT:httperror1.getcode()
->RET:404
<-PYT:httperror1.getcode()
->RET:404
<-PYT:httperror1.read()
->RET:(b'{"$id":"1","innerException":null,"message":"TF401232: Work item 999999 does not exist, or you do not have permissions to rea'
 b'd it.","typeName":"Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemUnauthorizedAccessException, Microsoft.TeamFound'
 b'ation.WorkItemTracking.Server","typeKey":"WorkItemUnauthorizedAccessException","errorCode":0,"eventId":3200}')
